### ISSUE TITLE
offset imported sample start time

### ISSUE THREAD

**Issue by dndrks** [dndrks/cheat_codes#1]
**current behavior**: an imported sample will clamp to the following 8 second ranges upon import
```
slot 1: 1-9 seconds
slot 2: 9-17 seconds
slot 3: 17-25 seconds
```

**proposed behavior** : an imported sample will clamp to 60 second ranges, the window can be adjusted by the user

**Comment by andr-ew** [comment]
WOW - this is exactly the thing I'm looking for

very happy to help implement this weekend if helpful ?

**Comment by dndrks** [comment]
implemented dynamic sample loading, up to 32 seconds, in 2.0 RC!
